baseurl = "https://vishwaravi.github.io/blog/"
languageCode = "en-us"
title = "Vishwa's Tech Blog"
theme = "terminal"
pagination.pagerSize = 5

# Required for terminal theme
[markup.goldmark.renderer]
  unsafe = true

[params]
  # dir name of your main content (default is `content/posts`)
  contentTypeName = "posts"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # set theme to full screen width
  fullWidthTheme = false
  # center theme with default width
  centerTheme = false

[languages]
  [languages.en]
    title = "Vishwa's Tech Blog"
    subtitle = "A developer's journey through code, systems, and technology"
    keywords = "programming, linux, mysql, development, tech blog"
    copyright = "© 2025 Vishwa Ravi"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "~/vishwa"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"